version: '3.8'

services:
  app:
    image: my-golang-app
    build: .
    
    depends_on:
      - mqtt
    ports:
      - "8000:8000"

  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
